config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'search', to: 'search#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable do
      member do
        post :select_best
      end
    end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :create

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy], shallow: true do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Authorable
  include Votable
  include Linkable
  include Commentable

  has_many :answers, -> { order('best DESC, created_at') }, dependent: :delete_all
  has_many :subscriptions, dependent: :delete_all
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :create_subscription

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def create_subscription
    user.subscriptions.find_or_create_by(question_id: id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show update destroy]
  authorize_resource

  def index
    @questions = Question.order(:created_at)
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionShowSerializer
  end

  def create
    @question = current_resource_owner.questions.create!(question_params)
    json_response(@question, :created)
  end

  def update
    @question.update(question_params)
    json_response(@question)
  end

  def destroy
    @question.destroy
    head :no_content
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[name url],
      reward_attributes: %i[title file]
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_gon_user_id, only: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  after_action :publish_question, only: :create

  include Voted

  authorize_resource

  def index
    @questions = Question.order(:created_at)
  end

  def show
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
    @question.build_reward
  end

  def edit
  end

  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    unless current_user.author_of?(@question)
      return redirect_to questions_path, notice: 'Delete unavailable! You are not the author of the question.'
    end

    @question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted.'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      QuestionSerializer.new(@question).to_json
    )
  end

  def set_gon_user_id
    gon.user_id = current_user&.id
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[name url],
      reward_attributes: %i[title file]
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_form_options(question)
    if question.new_record?
      {model: question, local: true}
    else
      {model: question, class: 'hidden', id: "edit-question-#{question.id}"}
    end
  end
end

app/views/questions/_add_comment_modal.html.erb
<div class="modal fade" id="addCommentModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_with scope: :comment, url: '#' do |form| %>
        <div class="modal-body">
          <div class="errors">
          </div>

          <div class="form-group">
            <%= form.text_area :body, placeholder: 'New comment', class: 'form-control' %>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit('Save', class: 'btn btn-primary') %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/questions/_buttons.html.slim
.buttons
  - if current_user
    - if current_user.author_of?(question)
      = render 'questions/form', question: question

      - if can?(:destroy, question)
        = link_to('Delete question', question_path(question), method: :delete, class: 'card-link',
                data: {confirm: 'Are you sure?'})
      - if can?(:update, question)
        = link_to('Edit question', '#', class: 'card-link edit-question-link', data: {question_id: question.id})

    - if can?(:create, Subscription)
      = link_to('Subscribe', question_subscriptions_path(question), method: :post, remote: true,
              class: "card-link subscribe-question-link #{current_user.subscribed?(question) ? 'hidden' : ''}")
    - if can?(:destroy, Subscription)
      = link_to('Unsubscribe', subscription_path(question), method: :delete, remote: true,
              class: "card-link unsubscribe-question-link #{current_user.subscribed?(question) ? '' : 'hidden'}")
    - if can?(:down, question)
      = link_to('Down!', down_question_path(question), method: :post, remote: true,
              class: "card-link down-question-link #{current_user.voted?(question) ? 'hidden' : ''}")
    - if can?(:up, question)
      = link_to('Up!', up_question_path(question), method: :post, remote: true,
              class: "card-link up-question-link #{current_user.voted?(question) ? 'hidden' : ''}")
    - if can?(:cancel_vote, question)
      = link_to('Cancel vote', cancel_vote_question_path(question), method: :post, remote: true,
              class: "card-link cancel-vote-question-link #{current_user.voted?(question) ? '' : 'hidden'}")

    = link_to('Add comment', '#',
            class: 'card-link add-comment-link',
            data: {url: comments_path(id: question, commentable: 'questions')})

app/views/questions/_form.html.slim
= form_with question_form_options(question) do |f|
  #question-errors
    = render 'shared/errors', resource: question

  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  = f.fields_for :reward do |reward|
    p
      = reward.label :title, 'Reward title'
      = reward.text_field :title
    p
      = reward.label :file, 'Reward file'
      = reward.file_field :file

  .question-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit question.new_record? ? 'Ask' : 'Update'

app/views/questions/_question.html.slim
.card.question id="question-#{@question.id}" data-question-id=@question.id
  .card-body
    h5.card-title= @question.title
    p.card-text
      strong= "Rating: "
      span.rating= @question.rating
    p.card-text= @question.body

    - if @question.files.attached?
      = render partial: "attachments/attachment", collection: @question.files

    - if @question.reward
      = render @question.reward

    - if @question.links.present?
      = render 'links/index', resource: @question

    = render 'questions/buttons', question: @question

    ul.comments.list-group.list-group-flush
      = render @question.comments.order(:created_at)

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  h1 Questions

  table.questions.table.table-striped
    thead.thead-light
      tr
        th scope="col" Question
    tbody
      - @questions.each do |question|
        tr
          td scope="row"
            = link_to question.title, question

  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'questions/form', question: @question

app/views/questions/show.html.slim
- cache @question do
  = render @question

  .answers
    = render @question.answers.reject(&:new_record?)

  - if user_signed_in?
    = render 'add_comment_modal'

    .card.mt-3#new-answer
      .card-body
        = render 'answers/form', answer: @answer

app/views/questions/subscribe.js.erb
$('.subscribe-question-link').hide()
$('.unsubscribe-question-link').show()

app/views/questions/unsubscribe.js.erb
$('.subscribe-question-link').show()
$('.unsubscribe-question-link').hide()

app/views/questions/update.js.erb
<% if @question.links.any?(&:gist?) %>
  window.location.reload(false); // иначе не подгружается вставляемый в партиале answer script
<% else %>
  <% if @question.errors.blank? %>
    $('#question-<%= @question.id %>').html('<%= j render @question %>');
  <% else %>
    $('#question-errors').html('<%= render 'shared/errors', resource: @question %>');
  <% end %>
<% end %>