config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'search', to: 'search#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable do
      member do
        post :select_best
      end
    end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :create

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy], shallow: true do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    authorize! :index, :search
    @results = Services::Search.new(params[:context], params[:q]).call
  end
end

app/views/search/_answer.html.slim
h3 Answer
h4 = link_to object.body, question_path(object.question)

app/views/search/_comment.html.slim
h3 Comment
h4 = link_to object.body, question_path(object.commentable.is_a?(Question) ? object.commentable : object.commentable.question)

app/views/search/_form.html.slim
= form_tag search_path, method: :get do
  = text_field_tag :q, params[:q], type: 'search', placeholder: 'Search'
  = select_tag :context, options_for_select(%w[All Question Answer Comment User], params[:context])
  = submit_tag 'Search'

app/views/search/_question.html.slim
h3 Question
h4 = link_to object.title, question_path(object)

app/views/search/_user.html.slim
h3 User
h4 = object.email

app/views/search/index.html.slim
h2 Search results:
- @results.each do |object|
  = render "search/#{object.class.name.underscore}", object: object