config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'search', to: 'search#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable do
      member do
        post :select_best
      end
    end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :create

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy], shallow: true do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @attachment = ActiveStorage::Attachment.find(params[:id])
    authorize! :destroy, @attachment
    @attachment.purge if current_user.author_of?(@attachment.record)
  end
end

app/views/attachments/_attachment.html.slim
p id="attachment-#{attachment.id}"
  = link_to attachment.filename.to_s, url_for(attachment)

  - if current_user&.author_of?(attachment.record)
    = " | "
    = link_to('Delete file', attachment_path(attachment), method: :delete, remote: true,
            data: {confirm: 'Are you sure?'})

app/views/attachments/destroy.js.erb
$('#attachment-<%= @attachment.id %>').html('');