config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'search', to: 'search#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable do
      member do
        post :select_best
      end
    end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :create

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy], shallow: true do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authorable
  include Votable
  include Linkable
  include Commentable

  belongs_to :question, touch: true

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: {message: "Answer can't be blank"}

  after_commit :send_notification, on: :create

  def select_best!
    Answer.transaction do
      Answer.where(question_id: question_id).update_all(best: false)
      question.reward&.update!(user_id: user_id)
      update!(best: true)
    end
  end

  private

  def send_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :load_answer, only: %i[show edit update destroy select_best]
  after_action :publish_answer, only: :create

  include Voted

  authorize_resource

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  def select_best
    @answer.select_best! if current_user.author_of?(@answer)
  end

  private

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question_#{@answer.question_id}_answers",
      AnswerSerializer.new(@answer).to_json
    )
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: %i[index create]
  before_action :load_answer, only: %i[show update destroy]
  authorize_resource

  def index
    render json: @question.answers
  end

  def show
    render json: @answer, serializer: AnswerShowSerializer
  end

  def create
    @answer = @question.answers.create!(answer_params.merge(user_id: current_resource_owner.id))
    json_response(@answer, :created)
  end

  def update
    @answer.update(answer_params)
    json_response(@answer)
  end

  def destroy
    @answer.destroy
    head :no_content
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_form_options(answer)
    if answer.new_record?
      {model: [answer.question, answer]}
    else
      {model: answer, class: 'hidden', id: "edit-answer-#{answer.id}"}
    end
  end

  def answer_errors_div_id(answer)
    answer.new_record? ? 'new-answer-errors' : "answer-#{answer.id}-errors"
  end
end

app/views/answers/_answer.html.slim
- cache answer do
  .card.answer.mt-3 id="answer-#{answer.id}"
    .card-body
      - if answer.best?
        p.best-answer-title.card-text This is best answer!

      p.card-text
        strong= "Rating: "
        span.rating= answer.rating
      p.card-text= answer.body

      - if answer.files.attached?
        = render partial: "attachments/attachment", collection: answer.files

      - if answer.links.present?
        = render 'links/index', resource: answer

      = render 'answers/buttons', answer: answer

      ul.comments.list-group.list-group-flush
        = render answer.comments.order(:created_at)

app/views/answers/_buttons.html.slim
.buttons
  - if current_user
    - if current_user.author_of?(answer)
      = render 'answers/form', answer: answer

      - if can?(:destroy, answer)
        = link_to('Delete answer', answer_path(answer), method: :delete, remote: true, data: {confirm: 'Are you sure?'},
                class: 'card-link')
      - unless answer.best?
        = link_to('Select best!', select_best_answer_path(answer), class: 'card-link best-answer-link',
                method: :post, remote: true)
      - if can?(:update, answer)
        = link_to('Edit answer', '#', class: 'card-link edit-answer-link', data: {answer_id: answer.id})

    - if can?(:down, answer)
      = link_to('Down!', down_answer_path(answer), method: :post, remote: true,
              class: "card-link down-answer-link #{current_user.voted?(answer) ? 'hidden' : ''}")
    - if can?(:up, answer)
      = link_to('Up!', up_answer_path(answer), method: :post, remote: true,
              class: "card-link up-answer-link #{current_user.voted?(answer) ? 'hidden' : ''}")
    - if can?(:cancel_vote, answer)
      = link_to('Cancel vote', cancel_vote_answer_path(answer), method: :post, remote: true,
              class: "card-link cancel-vote-answer-link #{current_user.voted?(answer) ? '' : 'hidden'}")

    = link_to('Add comment', '#',
            class: 'card-link add-comment-link',
            data: {url: comments_path(id: answer, commentable: 'answers')})

app/views/answers/_form.html.slim
= form_with answer_form_options(answer) do |f|
  div id=answer_errors_div_id(answer)
    = render 'shared/short_errors', resource: answer

  .form-group
    p= f.text_area :body, placeholder: 'New answer', class: 'form-control'

  .custom-file
    = f.label :files, class: 'custom-file-label'
    = f.file_field :files, multiple: true, direct_upload: true, class: 'custom-file-input'

  .answer-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  = f.submit(answer.new_record? ? 'Reply' : 'Save', class: 'btn btn-secondary')

app/views/answers/create.js.erb
<% if @answer.links.any?(&:gist?) %>
  window.location.reload(false); // иначе не подгружается вставляемый в партиале answer script
<% else %>
  $('#new-answer-errors').html('<%= render 'shared/short_errors', resource: @answer %>');

  <% if @answer.persisted? %>
    $('.answers').append('<%= j render @answer %>');
    $('#new-answer #answer_body').val('');
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').html('');

app/views/answers/select_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/update.js.erb
<% if @answer.links.any?(&:gist?) %>
  window.location.reload(false); // иначе не подгружается вставляемый в партиале answer script
<% else %>
  <% if @answer.errors.blank? %>
    $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
  <% else %>
    $('#answer-<%= @answer.id %>-errors').html('<%= render 'shared/short_errors', resource: @answer %>');
  <% end %>
<% end %>